### PR TITLE
Remove appended new line after img tag

### PR DESCRIPTION
**Pull request by axllent**
Remove the new line appended to `$Image` in templates

eg:

```
<a href="/">$Image</a>
```
currently results in
```
<a href="/"><img .... />
</a>
```

### CODE REVIEW

**Comment by dhensby** [comment]
Interesting, maybe we should trip template rendered strings because having new-lines at the end of files is pretty common/normal so this is likely a systemic issue.

**Comment by axllent** [comment]
Agreed, that would be a better {and safer) solution all round.

**Comment by michalkleiner** [comment]
+1 for trimming template-rendered strings

**Comment by dhensby** [comment]
I presume if this code is changed to the that `file_get_contents()` call is `rtrim()` for new lines, we should be good?

https://github.com/silverstripe/silverstripe-framework/blob/4/src/View/SSTemplateParser.peg#L1338-L1341

**Comment by michalkleiner** [comment]
Yep, that sounds like the safest option, though I wonder whether we want to do a general `trim` on all whitespace characters if we're touching this. Do we need possible leading whitespace chars preserved for any reason?

**Comment by dhensby** [comment]
I think leading whitespace characters in templates are much less likely to be there by accident, whereas lots of IDEs and `.editorconfig` setups will mandate new lines at the end of files (which the SS repos do), which is why I'm cautious about this PR - anyone editing a template will add accidental new lines by mistake.

There is *some* risk associated with trimming whitespace from the end of files, for example if the content is in a `<pre>` block, where whitespace matters... but that feels less likely and less of an issue than *adding* unexpected whitespace to inline elements like we are seeing here.

**Comment by kinglozzer** [comment]
I knew I’d seen some discussion about this before! https://github.com/silverstripe/silverstripe-framework/issues/4896

**Comment by dhensby** [comment]
Oh the rabbit hole of templating. I was just thinking about what joy it would be to rewrite the whole thing 😅

**Comment by GuySartorelli** [comment]
Closing as it sounds like there are preferred alternatives solutions.

**Comment by axllent** [comment]
Unless I'm missing something, I'm not sure a 6-year-old (unimplemented) RFC can be considered a valid alternative solution.

**Comment by GuySartorelli** [comment]
There was discussion above about trimming rendered templates globally, which commenters above (including yourself, stating "that would be a better {and safer) solution all round") agreed would be preferable to this PR's solution. I was referring to that more so than the RFC.

**Pull request closed without merging**
