### PR TITLE
FIX: Fixes #352 with guard for Folder query result

### LINKED ISSUE #352: Task fails with incomplete folder check
On line 103 of `SecureAssetsMigrationHelper.php`, the query for the `Folder` `DataObject` subclass naively assumes a record will always be returned, which of course is rarely always the case. Therefore a guard should be added before calling the method (any method) `getFilename()` on a potentially `null` query result:

FROM:

`$migratedPath = $this->migrateFolder($filesystem, $folder->getFilename());`

TO:

```
/** @var Folder $folder */
if (!$folder = Folder::get()->byID($id)) {
    $this->logger->info('Folder not found, skipping');
    continue;
}

$migratedPath = $this->migrateFolder($filesystem, $folder->getFilename());
```

### PR DESCRIPTION
**Pull request by phptek**
Fixes #352

### CODE REVIEW

**Comment by phptek** [comment]
I created the patch off "master". Let me know if that should have come out of "1" instead :-)

**Comment by Cheddam** [comment]
@phptek Thanks for raising this PR! If you want the fix to be released in the next minor release (4.6.0, as 4.5 has already been branched in preparation for release), you'll want to target the `1` branch. If you'd like it to appear in a patch update to a current minor release, you'll want to target it to the corresponding `1.x` branch. `master` tracks the next _major_ version, so you'd be waiting a while for that to be released 😉

My recommendation would be to target `1.5`.

**Comment by robbieaverill** [comment]
I've rebased onto 1.5 👍

**Comment by phptek** [comment]
Cheers @robbieaverill Any chance of a release tag so I can stop running off a fork? Thanks :-)

**Comment by Cheddam** [comment]
@phptek You can specify `1.5.x-dev` to run the development branch until a release is created.

**Pull request merged**
