### PR TITLE
More verbose file migration logging

### PR DESCRIPTION
**Pull request by chillu**
The log interval was useful to see errors in the noise,
but it's also masked what the task actually does.
Since this is moving and modifying project data,
it should be verbose by default. This will help answer
question later on, e.g. "why wasn't this file migrated".

A new message at the bottom which spells out how many files failed (if any)
makes it clear that you need to review the logs in detail (even though the error lines might hide between a lot of success lines).

### CODE REVIEW

**Comment by unclecheese** [comment]
There are default logging handlers (StreamHandler). But by not calling `pushHandler [ HTTPOutputHandler ]` on this implementation, we can limit a lot of the noise.

**Comment by robbieaverill** [comment]
Oh, TIL. /me goes and updates a module where it shouldn't have any handlers by default to have a NullHandler =D

**Comment by unclecheese** [comment]
Yeah it's a bit of magic in `Monolog\Logger`  ¯\_(ツ)_/¯

```php
    public function addRecord($level, $message, array $context = array())
    {
        if (!$this->handlers) {
            $this->pushHandler(new StreamHandler('php://stderr', static::DEBUG));
        }
```

**Comment by robbieaverill** [comment]
@unclecheese FYI the default LoggerInterface implementation in core is now a user logger rather than a core logger, and doesn't have any handlers attached by default. Do you see any issue with having a StreamHandler for it? 

Context: https://github.com/silverstripe/silverstripe-framework/blob/4/_config/logging.yml#L19-L25

**Pull request merged**
