### PR TITLE
BUG Fix hash redirection logic on PostreSQL and add PostreSQL to the travis matrix

### PR DESCRIPTION
**Pull request by maxime-rainville**
The recent permalink fix broken postgresql.

I fix the immediate issue and added PostgreSQL to the travis matrix.

### CODE REVIEW

**Comment by robbieaverill** [comment]
You’ll need to add the Postgres module - doesn’t look like it’s there yet judging by the Travis failure

**Comment by dnsl48** [comment]
something wicked is going on. I can clearly see postgres installation in .travis.yml, but Travis seems to run a completely different thing. the commit hashes don't even match...

**Comment by dnsl48** [comment]
here's the actual bulid - https://travis-ci.org/open-sausages/silverstripe-assets/jobs/517636831
It's green

**Comment by ScopeyNZ** [comment]
Btw this PR broke the builds: https://travis-ci.org/silverstripe/silverstripe-assets/jobs/517990937 .

It's fair to say that the open-sausages forks builds are not the same as the builds on this repo. Perhaps @maxime-rainville's PR branch wasn't fully up to date with the target branch?

**Comment by dnsl48** [comment]
Yes, although the diff has correct changes, the branch 4 does not have correct travis configs, which hasn't been merged up from 1.0.
Here is the follow up:
 - https://github.com/silverstripe/silverstripe-assets/pull/238

**Pull request merged**
